/**
 * Message Vault Utilities
 * Handles saved/starred messages with tagging
 */

export interface VaultMessage {
  messageId: string;
  roomId: string;
  text: string;
  senderName: string;
  senderId: string;
  timestamp: Date;
  tags: string[];
  aiTags?: string[]; // Generated by Gemini
  notes?: string; // User notes about message
  savedAt: Date;
}

/**
 * Determine if message is starred/saved
 */
export function isMessageVaulted(
  messageId: string,
  vaultMessages: VaultMessage[]
): boolean {
  return vaultMessages.some(vm => vm.messageId === messageId);
}

/**
 * Get vault message details
 */
export function getVaultMessage(
  messageId: string,
  vaultMessages: VaultMessage[]
): VaultMessage | null {
  return vaultMessages.find(vm => vm.messageId === messageId) || null;
}

/**
 * Format tag for display (remove # and capitalize)
 */
export function formatTag(tag: string): string {
  return tag.replace(/^#/, '').charAt(0).toUpperCase() + tag.replace(/^#/, '').slice(1);
}

/**
 * Add tag to message in vault
 */
export function addTagToMessage(
  messageId: string,
  tag: string,
  vaultMessages: VaultMessage[]
): VaultMessage[] {
  return vaultMessages.map(vm => {
    if (vm.messageId === messageId && !vm.tags.includes(tag)) {
      return {
        ...vm,
        tags: [...vm.tags, tag]
      };
    }
    return vm;
  });
}

/**
 * Remove tag from message in vault
 */
export function removeTagFromMessage(
  messageId: string,
  tag: string,
  vaultMessages: VaultMessage[]
): VaultMessage[] {
  return vaultMessages.map(vm => {
    if (vm.messageId === messageId) {
      return {
        ...vm,
        tags: vm.tags.filter(t => t !== tag)
      };
    }
    return vm;
  });
}

/**
 * Get all unique tags from vault messages
 */
export function getAllTags(vaultMessages: VaultMessage[]): string[] {
  const tags = new Set<string>();
  vaultMessages.forEach(vm => {
    vm.tags.forEach(tag => tags.add(tag));
  });
  return Array.from(tags).sort();
}

/**
 * Filter vault messages by tags
 */
export function filterByTags(
  tags: string[],
  vaultMessages: VaultMessage[]
): VaultMessage[] {
  if (tags.length === 0) return vaultMessages;
  
  return vaultMessages.filter(vm =>
    tags.every(tag => vm.tags.includes(tag))
  );
}

/**
 * Search vault messages by text
 */
export function searchVault(
  query: string,
  vaultMessages: VaultMessage[]
): VaultMessage[] {
  const lowerQuery = query.toLowerCase();
  
  return vaultMessages.filter(vm =>
    vm.text.toLowerCase().includes(lowerQuery) ||
    vm.senderName.toLowerCase().includes(lowerQuery) ||
    vm.tags.some(tag => tag.toLowerCase().includes(lowerQuery)) ||
    vm.notes?.toLowerCase().includes(lowerQuery)
  );
}

/**
 * Sort vault messages by date
 */
export function sortByDate(
  vaultMessages: VaultMessage[],
  order: 'asc' | 'desc' = 'desc'
): VaultMessage[] {
  return [...vaultMessages].sort((a, b) => {
    const aTime = new Date(a.timestamp).getTime();
    const bTime = new Date(b.timestamp).getTime();
    return order === 'desc' ? bTime - aTime : aTime - bTime;
  });
}

/**
 * Sort vault messages by saved date
 */
export function sortBySavedDate(
  vaultMessages: VaultMessage[],
  order: 'asc' | 'desc' = 'desc'
): VaultMessage[] {
  return [...vaultMessages].sort((a, b) => {
    const aTime = new Date(a.savedAt).getTime();
    const bTime = new Date(b.savedAt).getTime();
    return order === 'desc' ? bTime - aTime : aTime - bTime;
  });
}

/**
 * Generate AI tags for a message using Gemini
 */
export async function generateAITags(messageText: string): Promise<string[]> {
  const apiKey = import.meta.env.VITE_GEMINI_API_KEY;
  
  if (!apiKey) {
    throw new Error('Gemini API key not configured');
  }
  
  const prompt = `Analyze this message and generate 3-5 relevant, concise tags (one word or short phrase each). Return only the tags separated by commas, no explanation.

Message: "${messageText}"

Tags:`;
  
  try {
    const response = await fetch(
      'https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=' + apiKey,
      {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          contents: [{
            parts: [{ text: prompt }]
          }]
        })
      }
    );
    
    if (!response.ok) {
      throw new Error(`Gemini API error: ${response.status}`);
    }
    
    const data = await response.json();
    
    if (!data.candidates || !data.candidates[0]) {
      throw new Error('No tags response from Gemini');
    }
    
    const tagsText = data.candidates[0].content.parts[0].text.trim();
    return tagsText
      .split(',')
      .map((tag: string) => tag.trim().toLowerCase())
      .filter((tag: string) => tag.length > 0)
      .slice(0, 5); // Max 5 tags
  } catch (error) {
    console.error('AI tag generation error:', error);
    throw error;
  }
}

/**
 * Get statistics about vault
 */
export function getVaultStats(vaultMessages: VaultMessage[]) {
  return {
    totalMessages: vaultMessages.length,
    uniqueTags: new Set(vaultMessages.flatMap((vm: VaultMessage) => vm.tags)).size,
    messagesWithAITags: vaultMessages.filter(vm => vm.aiTags && vm.aiTags.length > 0).length,
    messagesWithNotes: vaultMessages.filter(vm => vm.notes && vm.notes.length > 0).length,
    earliestMessage: vaultMessages.length > 0 ? new Date(Math.min(...vaultMessages.map((vm: VaultMessage) => new Date(vm.timestamp).getTime()))) : null,
    latestMessage: vaultMessages.length > 0 ? new Date(Math.max(...vaultMessages.map((vm: VaultMessage) => new Date(vm.timestamp).getTime()))) : null,
  };
}
